TF1Plus: 403 when fetching index.mpd
Catch-up-TV-and-More/plugin.video.catchuptvandmore pull request #1428
Opened 2024-11-15 00:37 UTC by Nitorac

PR to fix [#1427](https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1427).
It has been tested successfully on LibreElec 12.0.1 with Kodi 21.1.0:
 - TF1Plus: The live channel is working 
 - A dozen of other FR channels are not impacted (live nor replay)

/!\: IMHO: it could be useful to make the `get_stream_with_quality` method differenciate the headers given to `inputstream.adaptive.stream_headers` (+ `inputstream.adaptive.manifest_headers`) and the headers given to the DRM license requests.
Because such a change should impact almost all already implemented channels, I have added a parameter to the method which emulates to old behavior when it's None, and used as I want when filled.

I'm open to improvments, I'm not really happy with the parameter name nor the "workaround" behavior !

2024-11-15 00:43 UTC, Nitorac commented
Revert to Draft since the testing may not have covered the use-case (https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/1427#issuecomment-2477711659)

2024-11-15 03:01 UTC, joaopa00 requested changes
Un petit changement de style pour garder la lisibilité du code:

```
# use custom_license_headers only if it is set, else fallback to stream_headers
if custom_license_headers:
    license_headers = urlencode(custom_license_headers)  
 else:
    license_headers = stream_headers
license_url = '%s|%s|R{SSM}|' % (license_url, license_headers)
```


au lieu de 

`
license_url = '%s|%s|R{SSM}|' % (license_url, urlencode(custom_license_headers) if custom_license_headers else stream_headers) # use custom_license_headers only if it is set, else fallback to stream_headers`

2024-11-16 01:16 UTC, joaopa00 commented
Flake8 complains (inline comment needs at least two spaces)

2024-11-16 22:44 UTC, Nitorac commented
(i'm still waiting for a DRM-protected show on TF1 to confirm that it fixes the issue !)

2024-11-16 22:47 UTC, joaopa00 commented
So I will wait for a few days before merging.

2024-11-26 17:19 UTC, joaopa00 commented
des nouvelles?

2024-11-26 19:06 UTC, Nitorac commented
Je regarde plusieurs fois par jour, et j'arrive toujours pas à en trouver, je vais me faire un petit robot pour surveiller quand est-ce qu'un flux protégé par Widevine passe sur tf1+.
Après si c'est embêtant que ça reste là, on peut fermer la PR et je renverrai un message ici quand j'aurai eu une émission qui pousse widevine et que j'aurai pu vérifier que le fix est correct !

2025-03-20 20:29 UTC, jeff2900 commented
Le fixe fonctionne pour le direct de TF1 ce soir. Match de Foot Ligue des Nations EUFA.

2025-03-20 20:32 UTC, Nitorac commented
J'allais envoyer un commentaire aussi !
Bonne nouvelle du coup, ils l'ont mis en place vers 17h.

2025-03-21 07:06 UTC, joaopa00 commented
On ffusionne donc?

2025-03-21 09:44 UTC, Nitorac commented
J'ai plus rien sur le feu pour cet issue, donc pour ma part c'est bon !

2025-03-21 16:54 UTC, merged